name: Grading

on:
  pull_request:
    branches: [ main ]

jobs:
  grading-test:
    runs-on: ubuntu-latest
    container: vladimirkutuev/cmocka:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Check repository clean
        run: ./1-grading-tests/scripts/check_clean.sh
      - name: Build
        run: ./1-grading-tests/scripts/build.sh

